"""empty message

Revision ID: 46131993453a
Revises: b67a1b6a4c39
Create Date: 2022-01-14 05:59:30.815068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46131993453a'
down_revision = 'b67a1b6a4c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
